### PR TITLE
Adding scalable effects for potion crafting

### PR DESCRIPTION
**Pull request by rdubs7041**
To support mods like Size Alchemy, I wanted to create new magic effects for the Growth, Size Limit, Essence, Might, and Shrink Resist potions that scaled based on the player's alchemy level. To do this, I updated the potion effect files to look for the new magic effects and read the magnitude value of the effect. Attached to this PR are screenshots of the new magic effects in the Creation Kit, as I wasn't exactly sure how to include this information in the repo. Thanks!

Effect of Might
Essence of Size
Growth
Shrink Resistance
Size Limit

### CODE REVIEW

**Comment by Sermitse** [comment]
I'm unsure about values like '**this->power = active_effect->magnitude > 0 ? active_effect->magnitude / 100.0f : 1.0f**;'
Isn't it easier to just do it like **this->power = std::clamp(active_effect->magnitude * 0.01f, 0.0f, 1000.0f);** ?

Or maybe just do **this->power = active_effect->magnitude * 0.01f**; in general

Also it would be nice if you would bbe able to send me ESP with new magic effects, preferably in separate ESP so i'll merge them into main ESP

**Comment by rdubs7041** [comment]
Ok, I've pushed up the separate ESP file to this PR. The reason why I went with using the ternary operator for the power calculations is that I wanted to ensure that any effects created with a magnitude less than or equal to 0 would simply apply the effect from the lowest tier of potion, rather than triggering a negative power.

**Comment by Sermitse** [comment]
I'll merge it a bit later but potions will continue to use old fixed values, you will have to edit potions to apply new effects on your end, also you can remove .esp now since i merged it with main GTS.esp

**Comment by rdubs7041** [comment]
Sounds good. esp file removed

**Comment by Sermitse** [comment]
Please try latest build from Github, i've included latest ESP (**GTS_Plugin\contrib\Distribution\GTS.esp**) and changed the way we change value a bit so it's just a matter of calling a single function, i haven't tested it though

**Comment by rdubs7041** [comment]
Looks like it still works to me. Created a test potion and tried it and it worked as expected.

**Pull request merged**
